version: '3'
services:
    pyramid:
        build: .
        container_name: pyramid
        command: pserve /app/server/development.ini --reload
        volumes:
            - .:/app
        ports:
            - 6543:6543