version: '3'
services:
    pyramid:
        build: .
        container_name: pyramid
        command: bash -c "pip install -e /app/server/ && pserve /app/server/development.ini --reload"
        volumes:
            - .:/app
        depends_on:
            - db
            - mongo
        ports:
            - "6543:6543"
    db:
        image: postgres:9.6
        restart: always
        container_name: eventme_postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1
            POSTGRES_DB: eventme
        volumes:
            - ~/.eventme-postgres:/var/lib/postgresql/data
        ports:
            - 5555:5432
    mongo:
        image: mongo
        restart: always
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/.eventme-mongo:/data/db
    mongoUser:
        image: mongo:latest
        container_name: mongoUser
        restart: on-failure:2
        links:
            - mongo:mongo
        command: mongo --host mongo --eval "db.getSiblingDB('eventme').createUser({user:'admin', pwd:'1', roles:[{role:'readWrite',db:'eventme'}]});"
        depends_on:
            - mongo
    adminer:
        image: dockette/adminer:full-php5
        restart: always
        depends_on:
           - db
           - mongo
        ports:
         - 9000:80
    client:
        image: node:10
        container_name: react
        command: bash -c "npm install && npm start"
        working_dir: /app/client
        volumes:
            - ./client:/app/client
        depends_on:
            - pyramid
        ports:
            - "3000:3000"